# Generated by Django 5.1 on 2024-08-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('token_pairing', models.CharField(choices=[('BTCUSDT', 'BTC/USDT'), ('ETHUSDT', 'ETH/USDT')], max_length=10)),
                ('leverage_used', models.IntegerField()),
                ('position_size', models.DecimalField(decimal_places=8, max_digits=20)),
                ('position_type', models.CharField(choices=[('Long', 'Long'), ('Short', 'Short')], max_length=5)),
                ('strategy_type', models.CharField(max_length=100)),
                ('timeframe', models.CharField(max_length=10)),
                ('opening_notes', models.TextField(blank=True, null=True)),
                ('pnl', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('result', models.CharField(blank=True, choices=[('TP', 'Take Profit'), ('SL', 'Stop Loss'), ('Cancelled', 'Cancelled')], max_length=10, null=True)),
                ('percentage_change', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('closing_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
