# Generated by Django 5.1 on 2024-08-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='date_time',
        ),
        migrations.AddField(
            model_name='trade',
            name='date',
            field=models.DateField(default='2024-08-30'),
        ),
        migrations.AddField(
            model_name='trade',
            name='time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='timeframe',
            field=models.CharField(choices=[('1min', '1 minute'), ('5min', '5 minutes'), ('15min', '15 minutes'), ('30min', '30 minutes'), ('1hr', '1 hour'), ('4hr', '4 hours'), ('8hr', '8 hours'), ('1day', '1 day')], max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='token_pairing',
            field=models.CharField(choices=[('BTCUSDTPERP', 'BTC/USDTPERP'), ('ETHUSDTPERP', 'ETH/USDTPERP'), ('XRPUSDTPERP', 'XRP/USDTPERP'), ('SOLUSDTPERP', 'SOL/USDTPERP'), ('DOGEUSDTPERP', 'DOGE/USDTPERP'), ('LTCUSDTPERP', 'LTC/USDTPERP'), ('LINKUSDTPERP', 'LINK/USDTPERP'), ('ADAUSDTPERP', 'ADA/USDTPERP'), ('MATICUSDTPERP', 'MATIC/USDTPERP'), ('DOTUSDTPERP', 'DOT/USDTPERP')], max_length=13),
        ),
    ]
