# Generated by Django 5.1 on 2024-08-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_remove_trade_date_time_trade_date_trade_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
    ]
